[package]
name = "struktur-main"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
miette = { version = "7.6.0", features = ["fancy"] }
pathdiff = "0.2.3"
struktur = { version = "*", path = "../lib" }
